version: '3'
services:
  postgresql:
    image: postgres
    container_name: movies_pgs
    environment:
      POSTGRES_DB: movies
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: movies_rmq
    hostname: movies_rmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
  management:
    build: ./management
    container_name: movies_management
    ports:
      - "9000:9000"
    depends_on:
      - postgresql
      - rabbitmq
  review:
    build: ./review_accept
    container_name: review_approving
    depends_on:
      - management